service: exercise2
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.helloWorld
    events:
      - http:
          method: get
          path: hello
